//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace UserManagement_App_DbFirst.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserHistories = new HashSet<UserHistory>();
        }

        public int UserID { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
        public string OldEmail { get; set; }
        public bool Active { get; set; }
        public System.DateTime Inserted { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }


        [Required]
        [Display(Name = "Contact")]
        public string Contact { get; set; }
        public int InsertedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public int UpdatedBy { get; set; }
        public bool Deleted { get; set; }
        public string Role { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserHistory> UserHistories { get; set; }
        public int TotalRecords { get; set; }
    }
}
