//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement_App_DbFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHistory
    {
        public int UserHistoryID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Inserted { get; set; }
        public int InsertedBy { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
        public string Contact { get; set; }
        public System.DateTime Updated { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
